package_rename_config:
  android:
    app_name: "My App" # (String) The display name of the android app
    package_name: "com.hiyob.app.myapp" # (String) The package name of the android app
    override_old_package: # (Optional) (String) Use this to delete the old folder structure of MainActivity or to use the existing code with the new package name
    lang: "kotlin" # (Optional) (String) The android development language {kotlin(default) or java}

  ios:
    app_name: "My App" # (String) The display name of the ios app
    bundle_name: "MyApp" # (String) The bundle name of the ios app
    package_name: "com.hiyob.app.myapp" # (String) The product bundle identifier of the ios app

  linux:
    app_name: "My App" # (String) The window title of the linux app
    package_name: "com.hiyob.app.myapp" # (String) The application id of the linux app
    exe_name: "my_app" # (String) The executable name (binary name) of the linux app

  macos:
    app_name: "My App" # (String) The product name of the macos app
    package_name: "com.hiyob.app.myapp" # (String) The product bundle identifier of the macos app
    copyright_notice:  "© 2025" # (String) The product copyright of the macos app

  web:
    app_name: "My App" # (String) The title of the web app and PWA
    short_app_name: "My App" # (String) The short display name of the PWA (Optional, defaults to app_name if not set)
    description: "A powerful tools." # (String) The description of the web app and PWA

  windows:
    app_name: "My App" # (String) The window title & software name of the windows app
    organization: "Hiyob" # (String) The organization name (company name) of the windows app
    copyright_notice: "© 2025" # (String) The legal copyright of the windows app
    exe_name: "myapp" # (String) The executable name (binary name) of the windows app